services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=501
      - PGID=20
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/config:/config
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - flaresolverr

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=501
      - PGID=20
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ../media/downloads:/downloads
    restart: unless-stopped
